<?php
$cookieData = $block->getCookieData();
$baseUrl = @$block->getBaseUrl();
?>
<?php
if ($cookieData == "")
    echo '<div style="display: inline;" class="your-location"> Edit your location</div>';
else {
    echo '<div style="display: inline;" class="your-location"> Your location : ' . $cookieData["city"] . '  ' . $cookieData["district"] . '  ' . $cookieData["ward"] . ' </div>';
}
?>
<div id="popup-modal" style="display:none">
    <div style="display: block; margin-bottom: 20px">
        <div style="width: 5% ; display: inline-block"><label for="city"><?= __("City :") ?></label></div> <?php // @todo Thêm dịch cho string khi in ra ?>
        <select id="city" style="width: 90%">
            <option value="">Select City</option>
            <?php
            foreach ($block->getListCity() as $key => $value):
                echo '<option value="' . $key . '">' . $value . '</option>';
            endforeach;
            ?>
        </select>
    </div>
    <div style="display: block; margin-bottom: 20px">
        <div style="width: 5% ; display: inline-block"><label for="district">District :</label></div>
        <select id="district" style="width: 90%">
            <option value="">Select City First</option>
        </select>
    </div>
    <div style="display: block">
        <div style="width: 5% ; display: inline-block"><label for="ward">Ward :</label></div>
        <select id="ward" style="width: 90%">
            <option value="">Select District First</option>
        </select>
    </div>
</div>
<script>
    require(['jquery'], function () { // @todo Thêm alias cho thư viện js được khai báo để viết rút gọn ở dưới ex:  require(['jquery'], function ($) { var a = $('.a') }
        jQuery(document).ready(function () {
            jQuery(document).on('click', '.your-location', function () {
                var options = {
                    type: 'popup',
                    responsive: true,
                    innerScroll: true,
                    title: 'Select your location',
                    'buttons': [{
                        text: jQuery.mage.__('Save your location'),
	                    class: "action primary",
                        click: function () {
                            this.closeModal();
                            let city = jQuery("#city option:selected").html();
                            let district = jQuery("#district option:selected").html();
                            let ward = jQuery("#ward option:selected").html();
                            let cityValue = jQuery('#city').val();
                            let districtValue = jQuery('#district').val();
                            let wardValue = jQuery('#ward').val();
                            if (cityValue === "") city = "";
                            if (districtValue === "") district = "";
                            if (wardValue === "") ward = "";
                            let requestUrl = <?php echo json_encode($block->getBaseUrl()) ?>+'location/location/save'; // @todo Không dùng nối string đối với url, dùng thư viện js của Magento mage/url hoặc $block->getUrl('url-path')
                            jQuery.ajax({ // Bên trên dùng $block->getUrl('location/location/save') cho kq tương tự, KHÔNG dùng let thay cho var, một số trình duyệt chưa hỗ trợ let của js
                                showLoader: true,
                                url: requestUrl,
                                data: {city: city, district: district, ward: ward},
                                type: "post",
                                dataType: 'json',
                            }).done(function (data) {
                                jQuery('.your-location').empty().append(data.value);
                            });
                        }
                    }]
                };
                jQuery("#popup-modal").modal(options).modal('openModal');
            });
            jQuery(document).on('change', '#city', function (e) {
                let selectedText = jQuery("#city option:selected").html();
                let param = 'district=' + jQuery('#city').val();
                let requestUrl = <?php echo json_encode($block->getBaseUrl()) ?>+'location/location/district';
                jQuery.ajax({
                    showLoader: true,
                    url: requestUrl,
                    data: param,
                    type: "GET",
                    dataType: 'json'
                }).done(function (data) {
                    jQuery('#district').empty().append(data.value);
                    jQuery('#ward').empty().append('<option value="">Select District First</option>');
                });
            });
            jQuery(document).on('change', '#district', function () {
                let param = 'ward=' + jQuery('#district').val();
                let requestUrl = <?php echo json_encode($block->getBaseUrl()) ?>+'location/location/ward';
                jQuery.ajax({
                    showLoader: true,
                    url: requestUrl,
                    data: param,
                    type: "GET",
                    dataType: 'json'
                }).done(function (data) {
                    jQuery('#ward').empty().append(data.value);
                });
            });
        });
    });
</script>


